#!/usr/bin/env python3

print("Starting download...")
print("Connected to server successfully!")
print("Downloading file: example-package.zip (15.2 MB)")
print("")
print("Average speed: 2.8 MB/s")
print("[██████████] 100% - Complete!")
print("")
print("=" * 40)
print("   DOWNLOAD COMPLETE!")
print("=" * 40)
print("")
print("    ✓ File saved successfully")
print("    ✓ Integrity check passed")
print("    ✓ Ready to use!")
print("")
print("     ╔═══════════════╗")
print("     ║   SUCCESS!    ║")
print("     ╚═══════════════╝")
print("")
print("Total time: 5.4 seconds")
print("File location: ./example-package.zip")